apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pipelines-easymode
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: components/pipelines-as-a-service/easymode
    repoURL: https://github.com/ploigos/argocd-tekton-reference.git
    targetRevision: gitops

  destination:
    namespace: pipelines-easymode
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      prune: false # The easymode pipeline isn't fully gitops friendly. The minimal pipeline is though!
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 50 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
