apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps
  namespace: devsecops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: argo-cd-apps/overlays/software-supply-chain-platform/ploigos-software-factory-operator
    repoURL: https://github.com/ploigos/argocd-tekton-reference.git
    targetRevision: minimal-defaults

  destination:
    namespace: devsecops
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
