apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-software-supply-chain
  namespace: devsecops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: argo-cd-apps/overlays/software-supply-chain-platform/devsecops
    repoURL: https://github.com/ploigos/openshift-pipelines-quickstart.git
    targetRevision: rekor

  destination:
    namespace: devsecops
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true