apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault-init
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: components/vault-init
    repoURL: https://github.com/twling/openshift-pipelines-quickstart.git
    targetRevision: vault

  destination:
    namespace: vault
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: 5 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 15s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
