apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quickstart-app-java-maven-cd
  namespace: openshift-gitops
  finalizers:
    - resources-finalizer.argocd.argoproj.io

spec:
  project: default

  source:
    path: components/example-apps/java-maven-cd
    repoURL: https://github.com/ploigos/ploigos-quickstart.git
    targetRevision: main

  destination:
    namespace: quickstart-app-java-maven-cd
    server: https://kubernetes.default.svc

  syncPolicy:

    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true

    retry:
      limit: -1 # number of failed sync attempt retries; unlimited number of attempts if less than 0
      backoff:
        duration: 10s # the amount to back off. Default unit is seconds, but could also be a duration (e.g. "2m", "1h")
        factor: 2 # a factor to multiply the base duration after each failed retry
        maxDuration: 3m # the maximum amount of time allowed for the backoff strategy
