apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nxrm-operator-certified
  namespace: openshift-operators
spec:
  channel: stable
  name: nxrm-operator-certified
  source: certified-operators
  sourceNamespace: openshift-marketplace
