apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cpp-make-minimal-el-route
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: el-cpp-make-minimal
    weight: 100
  wildcardPolicy: None
