apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rekor
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    project: default
    chart: rekor
    repoURL: https://sigstore.github.io/helm-charts
    targetRevision: 0.2.12
    helm:
      values: |
        server:
          ingress:
            enabled: false
  destination:
    namespace: sigstore
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 15s