apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rekor
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    chart: rekor
    repoURL: https://sigstore.github.io/helm-charts
    targetRevision: 0.2.12
    helm:
      values: |
        server:
          ingress:
            enabled: false