apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: nexus-operator
spec:
  channel: alpha
  installPlanApproval: Automatic
  name: nexus-operator
  source: redhatgov-operators
  sourceNamespace: openshift-marketplace
